# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Antora Default UI Hugo Theme"
license = "MPL-2.0"
licenselink = "https://github.com/basil/antora-default-ui-hugo-theme/blob/master/LICENSE"
description = "A port of the Antora default UI to Hugo"
homepage = "https://github.com/basil/antora-default-ui-hugo-theme"
tags = ["blog", "AsciiDoc", "Asciidoctor", "highlight.js", "syntax highlighting"]
features = ["blog", "AsciiDoc", "Asciidoctor", "highlight.js", "syntax highlighting"]
min_version = "0.41.0"

[author]
  name = "Basil Crow"
  homepage = "http://basilcrow.com/"

# If porting an existing theme
[original]
  name = "Antora Default UI"
  homepage = "https://docs.antora.org/antora-ui-default/"
  repo = "https://gitlab.com/antora/antora-ui-default"
